### ISSUE TITLE
Is this project dead? SPWR has updated the software since this was released

### ISSUE THREAD

**Issue by kaduffey** [rgallo/homebridge-sunpower#10]
Everything is in this subject and other outstanding issues.

If dead the project should be deleted or at least documented as abandoned?

**Comment by rgallo** [comment]
As detailed in this issue https://github.com/rgallo/homebridge-sunpower/issues/8#issuecomment-1169086134 I've been unable to figure out how to access the new API.  I'll add a message to the readme, I'm willing to get it working again if the API can be figured out.

**Comment by kaduffey** [comment]
ok, let me check my contacts at SPWR

**Comment by tbone7467** [comment]
@kaduffey any chance you got some information so we can get this back up and running? im excited about this

**Comment by kaduffey** [comment]
I poked him again, he had said he would check then I forgot to followup.

**Comment by knedd** [comment]
With the mySunPower app replaced by SunStrong Connect, is there any possibility of updating this plugin to work with the SunStron Connect API and credentials?
